package sk.tomas.chess;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'anx00283' at '5/12/17 2:48 PM' with Gradle 2.11
 *
 * @author anx00283, @date 5/12/17 2:48 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
